GET http://localhost:3000/questions

###

PUT http://localhost:3000/questions/6012f4ad44967a4c8c53ab32


###

GET http://localhost:3000/questions/6012f0f141e36c4a88b02e60
###


POST http://localhost:3000/questions/api/post
Content-Type: application/json 

[
{
    "title":"mock",
    "examID":"601581a78b1f87396d982259",
        "choices":[
        {"text":"prog language","isCorrect":false},
        {"text":"second","isCorrect":true},
        {"text":"third","isCorrect":false}
    ],
    "points":30

},
   { 
       "title":"mock 2?",
           "examID":"601581a78b1f87396d982259",
        "choices":[
        {"text":"prog language","isCorrect":false},
        {"text":"second","isCorrect":true},
        {"text":"third","isCorrect":false}
    ],
    "points":30
    }

]



###

POST http://localhost:3000/questions
Content-Type: application/json 

{
    "title":"What does the /etc/hosts file contains?",
        "choices":[
            {"text":"Hostnames of all devices on the network segment","isCorrect":false},
            {"text":"The IP address of the default gateway","isCorrect":false},
            {"text":"CPU and memory info","isCorrect":false},
            {"text":"IP addresses to hostnames mappings","isCorrect":true}
        ]
}




###

GET http://localhost:3000/questions/byexam/601584175e30003c042f7f7d

###



GET http://localhost:3000/exams

###

GET http://localhost:3000/exams/6017112eb0033f9c71e85a76
###
DELETE http://localhost:3000/questions/6016f1d30980997afe7a49ad


###
POST http://localhost:3000/exams
Content-Type:application/json

{
    "title":"C++ exam",
    "duration":60
}

###
GET http://localhost:3000/teachers/60142585c399b061d18410bb

###
DELETE http://localhost:3000/teachers/601424e547ad99614c093773

###

PUT http://localhost:3000/teachers/60142585c399b061d18410bb
Content-Type: application/json

{
  "firstName": "avihagever",
  "lastName": "nir",
  "username": "avinir2020"
}


###
GET http://localhost:3000/questions/getquestions/api

###
DELETE http://localhost:3000/exams/6016a4178f3c5233e8b62ef0