GET http://localhost:3000/questions

###

GET http://localhost:3000/questions/6012f0f141e36c4a88b02e60
###


POST http://localhost:3000/questions
Content-Type: application/json 

{
    "examID":2,
    "choices":[
        {"text":"choice a","isCorrect":false},
        {"text":"choice b","isCorrect":true},
        {"text":"choice c","isCorrect":false}
    ],
    "title":"second question",
    "points":30

}

###
DELETE http://localhost:3000/questions/6012f44444967a4c8c53ab31

###
POST http://localhost:3000/exams
Content-Type:application/json
{
    "examID":1,
    "title":"Java exam",
    "teacherID":2,
    "duration":60,
    "date":"16008688930050",
    "questions":[
        {
        }
    ]

}

###
GET http://localhost:3000/teachers/60142585c399b061d18410bb

###
DELETE http://localhost:3000/teachers/601424e547ad99614c093773

###

PUT http://localhost:3000/teachers/60142585c399b061d18410bb
Content-Type: application/json

{
  "firstName": "avi",
  "lastName": "nir",
  "email": "test@gmail.com",
  "password": "$2a$10$bKe8HXLWEu9XJAfGQfngkun.yPELuUxE.e9jCO3MyB/XxfsxpZV7i",
  "date": "1611933061579",
  "__v": 0
}