GET http://localhost:3000/questions

###

GET http://localhost:3000/questions/60242b23da4da5dbf68fc026
###
PUT http://localhost:3000/questions/6012f4ad44967a4c8c53ab32


###


GET http://localhost:3000/exams/getbyteacher/6019745802dd5a2914c2fa6e

###

GET http://localhost:3000/questions/
###


POST http://localhost:3000/questions/api/post
Content-Type: application/json 

[
{
    "title":"mock",
    "examID":"601581a78b1f87396d982259",
        "choices":[
        {"text":"prog language","isCorrect":false},
        {"text":"second","isCorrect":true},
        {"text":"third","isCorrect":false}
    ],
    "points":30

},
   { 
       "title":"mock 2?",
           "examID":"601581a78b1f87396d982259",
        "choices":[
        {"text":"prog language","isCorrect":false},
        {"text":"second","isCorrect":true},
        {"text":"third","isCorrect":false}
    ],
    "points":30
    }

]



###

POST http://localhost:3000/questions
Content-Type: application/json 

{
    "title":"What does the /etc/hosts file contains?",
        "choices":[
            {"text":"Hostnames of all devices on the network segment","isCorrect":false},
            {"text":"The IP address of the default gateway","isCorrect":false},
            {"text":"CPU and memory info","isCorrect":false},
            {"text":"IP addresses to hostnames mappings","isCorrect":true}
        ]
}




###

GET http://localhost:3000/questions/byexam/6024ea0ac24cce10f4a4830a

###



GET http://localhost:3000/exams



###
DELETE http://localhost:3000/exams/6041fef531e9921dfefcea20

###


GET http://localhost:3000/exams/6041fdd3630be81cfcd7e901
###
DELETE http://localhost:3000/questions/6016f1d30980997afe7a49ad


###
POST http://localhost:3000/exams
Content-Type:application/json

{
    "title":"teacherAdd exam test55",
    "duration":60,
    "teacherID":"6019745802dd5a2914c2fa6e"
    
}

###
GET http://localhost:3000/teachers/6019745802dd5a2914c2fa6e

###
DELETE http://localhost:3000/teachers/601424e547ad99614c093773

###

PUT http://localhost:3000/teachers/60142585c399b061d18410bb
Content-Type: application/json

{
  "firstName": "avihagever",
  "lastName": "nir",
  "username": "avinir2020"
}


###
GET http://localhost:3000/questions/getquestions/api

